name: Close issue if moved to Done column

on:
  project_card:
    types: [moved]

jobs:
  auto-close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if moved to Done column
        uses: actions/github-script@v6
        with:
          script: |
            const DONE_COLUMN_NAME = 'Done'; // Ensure this matches the name of your Done column exactly
            const cardId = github.context.payload.project_card.id;

            async function run() {
              // Fetch card details
              const { data: card } = await github.rest.projects.getCard({ card_id: cardId });
              if (!card.content_url) return;

              // Fetch column details
              const { data: column } = await github.rest.projects.getColumn({ column_id: card.column_id });
              if (column.name !== DONE_COLUMN_NAME) return;

              // Extract the issue number from the card's content_url
              const issueNumber = card.content_url.split('/').pop();

              // Close the issue
              await github.rest.issues.update({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                issue_number: issueNumber,
                state: 'closed'
              });
            }

            run();
          github-token: ${{ secrets.GITHUB_TOKEN }}
